services:
  appdaf:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdafdb
      POSTGRES_USER: appdaf
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - appdaf
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
